import express from 'express';
import { authenticate, normalizeRole } from '../middleware/auth';
import Student from '../models/Student';
import Teacher from '../models/Teacher';
import ClassFeeStructure from '../models/ClassFeeStructure';
import StudentInvoice from '../models/StudentInvoice';
import StudentFeePayment from '../models/StudentFeePayment';
import User from '../models/User';
import { runWithTenantStorage } from '../config/tenantStorage';
import { writeAuditLog } from '../services/auditService';

const router = express.Router();
const primaryDb = <T>(fn: () => Promise<T>) => runWithTenantStorage(null, fn);
const money = (v: any) => Math.round((Number(v || 0) + Number.EPSILON) * 100) / 100;
const ym = (src: any) => { const now = new Date(); return { month: Math.min(12, Math.max(1, Number(src?.month || now.getMonth() + 1))), year: Number(src?.year || now.getFullYear()) }; };
const invNo = (studentId: any, month: number, year: number) => `INV-${year}${String(month).padStart(2, '0')}-${String(studentId).slice(-6)}-${Date.now().toString().slice(-5)}`;
const receiptNo = () => `INV-RCPT-${Date.now()}-${Math.floor(Math.random() * 900 + 100)}`;
const allowed = ['head', 'assistant_head', 'finance_officer', 'class_teacher'];
function canOpen(req: any) { return allowed.includes(normalizeRole(req.user?.role)) || (req.user?.permissions || []).includes('manage:finance'); }
async function scope(req: any) { if (normalizeRole(req.user.role) !== 'class_teacher') return null; const t: any = await Teacher.findOne({ institutionId: req.user.institutionId, userId: req.user._id, isActive: { $ne: false } }).select('assignedClasses').lean(); return (t?.assignedClasses || []).map((x: any) => String(x?._id || x)); }
async function ensureInvoices(req: any, month: number, year: number) { const institutionId = req.user.institutionId; const structures = await ClassFeeStructure.find({ institutionId, feeType: 'monthly_tuition', isActive: true, $or: [{ effectiveFromYear: { $lt: year } }, { effectiveFromYear: year, effectiveFromMonth: { $lte: month } }] }).lean(); const latest = new Map<string, any>(); for (const s of structures) { const key = `${s.classId}:${s.section || 'All'}`; if (!latest.has(key)) latest.set(key, s); } for (const s of latest.values()) { const students = await Student.find({ institutionId, classId: s.classId, isActive: { $ne: false } }).select('_id').lean(); for (const st of students) { const exists = await StudentInvoice.exists({ institutionId, studentId: st._id, classId: s.classId, month, year, feeType: 'monthly_tuition' }); if (exists) continue; await StudentInvoice.create({ institutionId, studentId: st._id, classId: s.classId, section: s.section || 'All', month, year, feeType: 'monthly_tuition', invoiceNo: invNo(st._id, month, year), items: [{ name: 'Monthly Tuition Fee', amount: money(s.amount), discount: 0, lateFee: 0 }], totalAmount: money(s.amount), paidAmount: 0, dueAmount: money(s.amount), status: 'unpaid', dueDate: new Date(year, month - 1, Math.min(Number(s.dueDay || 10), 28)), generatedBy: req.user._id }); } } }
async function enrich(rows: any[]) { const ids = [...new Set(rows.map((s: any) => String(s.userId || '')).filter(Boolean))]; const users = await primaryDb(() => User.find({ _id: { $in: ids } }).select('name phone email avatar').lean()); const map = new Map(users.map((u: any) => [String(u._id), u])); return rows.map((s: any) => ({ ...s, userId: map.get(String(s.userId)) || s.userId })); }
router.use(authenticate);
router.use((req: any, res, next) => canOpen(req) ? next() : res.status(403).json({ message: 'Access denied. Finance collection only.' }));
router.get('/', async (req: any, res) => { try { const { month, year } = ym(req.query); await ensureInvoices(req, month, year); const q: any = { institutionId: req.user.institutionId, isActive: { $ne: false } }; const sc = await scope(req); if (sc) { if (!sc.length) return res.json({ students: [], month, year }); q.classId = { $in: sc }; } const students = await enrich(await Student.find(q).populate('classId', 'name grade').populate('sectionId', 'name').sort({ rollNumber: 1 }).lean()); const invoices = await StudentInvoice.find({ institutionId: req.user.institutionId, month, year, status: { $in: ['unpaid', 'partial', 'overdue'] } }).lean(); const term = String(req.query.search || '').toLowerCase(); const result = students.filter((s: any) => !term || [s.userId?.name, s.rollNumber, s.classId?.name, s.sectionId?.name].join(' ').toLowerCase().includes(term)).map((s: any) => ({ ...s, dueAmount: money(invoices.filter((i: any) => String(i.studentId) === String(s._id)).reduce((sum: number, i: any) => sum + Number(i.dueAmount || 0), 0)), selectedMonth: month, selectedYear: year })); res.json({ students: result, month, year }); } catch (error: any) { res.status(500).json({ message: error?.message || 'Failed to load selected month fees', error }); } });
router.post('/collect', async (req: any, res) => { try { const { month, year } = ym(req.body); await ensureInvoices(req, month, year); const student: any = await Student.findOne({ _id: req.body.studentId, institutionId: req.user.institutionId }).lean(); if (!student) return res.status(404).json({ message: 'Student not found.' }); const sc = await scope(req); if (sc && !sc.includes(String(student.classId))) return res.status(403).json({ message: 'Class Teacher can collect only assigned class fees.' }); const invoice: any = await StudentInvoice.findOne({ institutionId: req.user.institutionId, studentId: student._id, month, year, status: { $in: ['unpaid', 'partial', 'overdue'] } }).sort({ dueDate: 1 }); if (!invoice) return res.status(404).json({ message: `No due invoice found for selected month ${month}/${year}.` }); const paid = money(req.body.amount); if (paid <= 0 || paid > money(invoice.dueAmount)) return res.status(400).json({ message: 'Invalid amount for selected month.', dueAmount: invoice.dueAmount }); const record = await StudentFeePayment.create({ invoiceId: invoice._id, studentId: student._id, amount: paid, paymentMethod: req.body.paymentMethod || 'cash', status: 'verified', collectedBy: req.user._id, collectedByRole: normalizeRole(req.user.role), note: req.body.notes || `Offline monthly fee ${month}/${year}`, receiptNo: receiptNo(), institutionId: req.user.institutionId }); invoice.paidAmount = money(Number(invoice.paidAmount || 0) + paid); invoice.dueAmount = money(Number(invoice.totalAmount || 0) - Number(invoice.paidAmount || 0)); invoice.status = invoice.dueAmount <= 0 ? 'paid' : 'partial'; await invoice.save(); await writeAuditLog(req, 'create', 'selected-month-fee-collection', record._id, record).catch(() => undefined); res.status(201).json({ payment: record, invoice, month, year, message: 'Selected month fee collected successfully.' }); } catch (error: any) { res.status(500).json({ message: error?.message || 'Failed to collect selected month fee', error }); } });
export default router;
