import 'express-async-errors';
import express, { NextFunction, Request, Response } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import authRoutes from './routes/auth';
import configRoutes from './routes/config';
import seedRoutes from './routes/seed';
import demoResultRoutes from './routes/demoResults';
import userRoutes from './routes/users';
import studentRoutes from './routes/students';
import teacherRoutes from './routes/teachersDirect';
import staffRoutes from './routes/staffDirect';
import academicRoutes from './routes/academic';
import academicOverviewRoutes from './routes/academicOverviewSafe';
import studentResultRoutes from './routes/studentResults';
import resultRoutes from './routes/resultsSafe';
import publicResultRoutes from './routes/publicResults';
import academicClassRoutes from './routes/academicClasses';
import academicSubjectRoutes from './routes/subjectsSafe';
import academicExamRoutes from './routes/examsScoped';
import syllabusRoutes from './routes/syllabus';
import classRoutineRoutes from './routes/classRoutine';
import homeworkRoutes from './routes/homework';
import questionBankRoutes from './routes/questionBank';
import onlineClassRoutes from './routes/onlineClasses';
import attendancePeopleActiveRoutes from './routes/attendancePeopleActive';
import attendanceRoutes from './routes/attendance';
import attendanceMeRoutes from './routes/attendanceMe';
import leaveRoutes from './routes/leaves';
import holidayRoutes from './routes/holidays';
import financeRoutes from './routes/finance';
import financeMonthlyFeeRoutes from './routes/financeMonthlyFees';
import financeMonthCollectRoutes from './routes/financeMonthCollect';
import financeFeesDirectRoutes from './routes/financeFeesDirect';
import financeCollectionsDirectRoutes from './routes/financeCollectionsDirect';
import financePaymentsDirectRoutes from './routes/financePaymentsDirect';
import financeSalaryDirectRoutes from './routes/financeSalaryDirect';
import financeReportsDirectRoutes from './routes/financeReportsDirect';
import studentFeePaymentRoutes from './routes/studentFeePayments';
import payrollRoutes from './routes/payroll';
import promotionRoutes from './routes/promotions';
import documentRoutes from './routes/documents';
import noticeRoutes from './routes/notices';
import committeeRoutes from './routes/committee';
import parentRoutes from './routes/parent';
import idCardRoutes from './routes/idCard';
import dashboardRoutes from './routes/dashboard';
import notificationRoutes from './routes/notifications';
import messageRoutes from './routes/messages';
import reportRoutes from './routes/reports';
import backupRoutes from './routes/backup';
import institutionRoutes from './routes/institution';
import imageRoutes from './routes/images';
import admissionRoutes from './routes/admissions';
import adminRoutes from './routes/admin';
import smsRoutes from './routes/sms';
import smsMonitoringRoutes from './routes/smsMonitoring';
import libraryRoutes from './routes/library';
import siteSettingsRoutes from './routes/siteSettings';
import devTestRoutes from './routes/devTest';
import storageSyncRoutes from './routes/storageSync';
import SmsLog from './models/SmsLog';
import './models/allModels';
import { config } from './config/config';
import { resolveTenantStorageContext, runWithTenantStorage } from './config/tenantStorage';
import storageConfigGuard from './middlewares/storageConfigGuard';
import resolveTenant from './middleware/tenant';
import csrfRoutes from './routes/csrf';
import { csrfProtection, cookieParser } from './middlewares/csrf';
import { sanitizeRequest } from './middlewares/sanitize';
import { errorHandler, notFoundHandler } from './middlewares/errorHandler';
import { requestLogger, attachRequestId } from './middlewares/requestLogger';
import logger from './utils/logger';
import { loginLimiter, dashboardLimiter, reportLimiter, pdfLimiter } from './middlewares/rateLimiter';

const app = express();
app.set('trust proxy', 1);
const splitOrigins = (value?: string | null): string[] =>(value || '').split(',').map((origin) => origin.trim()).filter(Boolean).map((origin) => origin.replace(/\/$/, ''));
// Resolve CORS config lazily (after dotenv.config() has run in server.ts)
const getCorsConfig = () => {
  const cfg = config();
  const allowAllOrigins = String(process.env.CORS_ALLOW_ALL || '').toLowerCase() === 'true' || process.env.ALLOWED_ORIGINS === '*';
  const envOrigins = new Set<string>([cfg.frontendUrl, cfg.mobileUrl, cfg.androidUrl, cfg.staticServerUrl, ...splitOrigins(process.env.ALLOWED_ORIGINS), ...splitOrigins(process.env.FRONTEND_URL), ...splitOrigins(process.env.MOBILE_URL), ...splitOrigins(process.env.ANDROID_URL)].filter(Boolean));
  const CSRF_HEADER = (process.env.CSRF_HEADER_NAME || 'x-csrf-token');
  const allowedHeaders = new Set<string>(['Content-Type', 'Authorization', CSRF_HEADER, 'x-institution-id', 'X-Institution-Id', 'x-school-id', 'X-School-Id', 'Origin', 'X-Requested-With', 'Accept', 'x-access-token', 'X-Access-Token', ...splitOrigins(process.env.CORS_ALLOWED_HEADERS)].filter(Boolean));
  return { allowAllOrigins, envOrigins, allowedHeaders, CSRF_HEADER };
};
const isAllowedOrigin = (origin?: string): boolean => { const { allowAllOrigins, envOrigins } = getCorsConfig(); if (!origin || allowAllOrigins) return true; const normalized = origin.replace(/\/$/, ''); if (envOrigins.has(normalized)) return true; if (/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(normalized)) return true; if (/^https?:\/\/([a-z0-9-]+\.)*easyschool\.live$/i.test(normalized)) return true; return false; };
const setCorsHeaders = (req: Request, res: Response) => { const { allowedHeaders } = getCorsConfig(); const origin = req.headers.origin as string | undefined; if (origin && isAllowedOrigin(origin)) { res.header('Access-Control-Allow-Origin', origin); res.header('Vary', 'Origin'); res.header('Access-Control-Allow-Credentials', 'true'); } else if (!origin && process.env.NODE_ENV !== 'production') { res.header('Access-Control-Allow-Origin', '*'); } res.header('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS'); res.header('Access-Control-Allow-Headers', Array.from(allowedHeaders).join(', ')); res.header('Access-Control-Max-Age', process.env.CORS_MAX_AGE || '86400'); };
app.use((req, res, next) => { setCorsHeaders(req, res); if (req.method === 'OPTIONS') return res.status(204).end(); next(); });
app.use(cors({ origin: (origin, callback) => callback(null, isAllowedOrigin(origin || undefined)), credentials: true, methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'], allowedHeaders: Array.from(getCorsConfig().allowedHeaders), optionsSuccessStatus: 204 }));
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use('/api/institution/billing/stripe/webhook', express.raw({ type: 'application/json' }));
app.use(express.json({ limit: process.env.JSON_BODY_LIMIT || '50mb' }));
app.use(express.urlencoded({ extended: true, limit: process.env.URLENCODED_BODY_LIMIT || '50mb' }));
app.use(rateLimit({ windowMs: Number(process.env.RATE_LIMIT_WINDOW_MS || 60 * 1000), max: Number(process.env.RATE_LIMIT_MAX || 2000), standardHeaders: true, legacyHeaders: false, skip: (req) => req.method === 'OPTIONS' || ['/health', '/api/health', '/api', '/api/', '/api/auth/profile', '/api/notifications', '/api/messages/stats/unread', '/api/dashboard/stats', '/api/dashboard/charts'].includes(req.path) }));
app.use(resolveTenant);
app.use(storageConfigGuard);
app.use(attachRequestId);
app.use(requestLogger as any);
app.use(sanitizeRequest);
app.use(cookieParser);
app.use('/api/csrf', csrfRoutes);
if ((process.env.NODE_ENV || 'development').toLowerCase() === 'production') { app.use(csrfProtection); } else { logger.warn('⚠️ CSRF protection disabled in development mode'); }

app.use((req: any, res, next) => { const path = req.path; const isAuthWrite = path.startsWith('/api/auth') && !path.startsWith('/api/auth/profile'); const isUsersRoute = path.startsWith('/api/users'); if (isAuthWrite || isUsersRoute) return next(); const context = req.institution ? resolveTenantStorageContext(req.institution) : null; runWithTenantStorage(context, next, req.user, req.institution); });
app.use('/api/auth/login', loginLimiter);
app.use('/api/auth', authRoutes);
app.use('/api/config', configRoutes);
app.use('/api/seed', seedRoutes);
app.use('/api/demo-results', demoResultRoutes);
app.use('/api/users', userRoutes);
app.use('/api/students', studentRoutes);
app.use('/api/teachers', teacherRoutes);
app.use('/api/staff', staffRoutes);
app.use('/api/academic/public/results', publicResultRoutes);
app.use('/api/academic/classes', academicClassRoutes);
app.use('/api/academic/subjects', academicSubjectRoutes);
app.use('/api/academic/exams', academicExamRoutes);
app.use('/api/academic/results/me', studentResultRoutes);
app.use('/api/academic/results', resultRoutes);
app.use('/api/academic/report-card', reportLimiter);
app.use('/api/academic', academicOverviewRoutes);
app.use('/api/academic', academicRoutes);
app.use('/api/syllabus', syllabusRoutes);
app.use('/api/class-routines', classRoutineRoutes);
app.use('/api/homework', homeworkRoutes);
app.use('/api/question-bank', questionBankRoutes);
app.use('/api/online-classes', onlineClassRoutes);
app.use('/api/attendance', attendancePeopleActiveRoutes);
app.use('/api/attendance', attendanceMeRoutes);
app.use('/api/attendance', attendanceRoutes);
app.use('/api/leaves', leaveRoutes);
app.use('/api/holidays', holidayRoutes);
app.use('/api/finance/my-fees', studentFeePaymentRoutes);
app.use('/api/finance', financeMonthlyFeeRoutes);
app.use('/api/finance/month-collect', financeMonthCollectRoutes);
app.use('/api/finance/fees', financeFeesDirectRoutes);
app.use('/api/finance/collections', financeCollectionsDirectRoutes);
app.use('/api/finance/payments', financePaymentsDirectRoutes);
app.use('/api/finance/salary', financeSalaryDirectRoutes);
app.use('/api/finance/reports', financeReportsDirectRoutes);
app.use('/api/finance/audit/export', pdfLimiter);
app.use('/api/finance', financeRoutes);
app.use('/api/payroll', payrollRoutes);
app.use('/api/promotions', promotionRoutes);
app.use('/api/documents', documentRoutes);
app.use('/api/notices', noticeRoutes);
app.use('/api/committee', committeeRoutes);
app.use('/api/parent', parentRoutes);
app.use('/api/id-cards/render-pdf', pdfLimiter);
app.use('/api/id-cards', idCardRoutes);
app.use('/api/dashboard', dashboardLimiter, dashboardRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/messages', messageRoutes);
app.use('/api/reports', reportLimiter, reportRoutes);
app.use('/api/backup', backupRoutes);
app.use('/api/images', imageRoutes);
app.use('/api/institution', institutionRoutes);
app.use('/api/admissions', admissionRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/sms', smsRoutes);
app.use('/api/sms-monitoring', smsMonitoringRoutes);
app.use('/api/library', libraryRoutes);
app.use('/api/site-settings', siteSettingsRoutes);
app.use('/api/settings', siteSettingsRoutes);
app.use('/api/dev-test', devTestRoutes);
app.use('/api/storage-sync', storageSyncRoutes);
app.get(['/health', '/api/health'], async (_req, res) => { const mongoose = await import('mongoose'); const dbState = mongoose.default.connection.readyState; res.json({ status: 'OK', message: 'easy school Server is running', dbReadyState: dbState, dbConnected: dbState === 1, corsOrigins: getCorsConfig().envOrigins.size }); });
app.get(['/api', '/api/'], (_req, res) => { res.json({ success: true, message: 'easy school API is running' }); });
SmsLog.deleteMany({ createdAt: { $lt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000) } }).catch((error) => logger.warn('SMS log cleanup failed', { error: error.message }));
app.use(notFoundHandler);
app.use(errorHandler as any);
export default app;
